### ISSUE TITLE
Create GitHub Release

### ISSUE THREAD

**Issue by favoyang** [MartinGonzalez/unity-android-manifest-placeholders-resolver#1]
Hi @MartinGonzalez,

Thanks for contributing to OpenUPM. Please create a GitHub Release for your current version. The git tag should be x.y.z or vx.y.z format. Then our build pipelines can process your repository into  a UPM package.

Further reading: https://openupm.com/docs/adding-upm-package.html#handling-a-repository-without-git-tag

**Comment by MartinGonzalez** [comment]
Done!
